---
engines:
  duplication:
    # Too much noise with duplication?
    enabled: false
    config:
      languages:
        javascript:
          mass_threshold: 60
  eslint:
    enabled: true
  nodesecurity:
      enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- .idea
- node_modules/
- bin/
- test/
- coverage/
- data/
- public/
- config.example.js
