language: node_js
node_js:
  - 6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

services:
  - mongodb

env:
  - NODE_ENV=testing LIOW_DB_URL=mongodb://localhost/liow2 CXX=g++-4.8

before_script:
  - cp config.example.js config.js

after_success:
  - npm run test-cov
  - npm install -g codeclimate-test-reporter && codeclimate-test-reporter < ./coverage/lcov.info

notifications:
  webhooks:
    urls:
      - http://hook.loveisourweapon.com/bkbooth/liow2-server
    on_failure: never
    on_start: never
  slack:
    secure: q4LJ5hAqy568nqSSZnUUEPKzm3HDE5AcVeXoWJ2MbaRe6ZV74DZLdnJ4amdqWVaBgEVpl9ll6xQgRUTrxPML2B/FiCPcx6kOWu+Y4/kspMIg13DRB5PElgo8kUSiSE05EbVJGKPll4/5tOcqpRaom5WwW2WXfMSFSgHUi0uOW1cNbUVgzq7DkFVCIceyorJffRPjO+nA1aTotfwMxvw4Re5wSnCQQ+fuZFLpMW7W0oJihaWDBQGNG9nGucYWcMbkoTAIUgm7ZV/+wtcNIAFVH/pBgFjy2Uo3KkTmhslDHE3UO9+bj3VftBoGXf7TuO9T1YpNoIfSVrVInctK/C8eMJjmdtF4LStOz33+/j4Zc+BdxFpQDyoUI9p9fbBu1yLkD0RFnJTQ12gftrDWMO3AC9Y7SH2TMy3QuJ5f7hIk9gymROs14uAU4KGrd8IWKIfJg9TgkUm4qMxG+MuYCeqnNkPjIS8OjCa9723gQ612Ne8Q9XxC+5rKAKXANpwaXNeGKZ+iixGRh2lrGt6MoeZudIJJTlhymK3rK18k82MQp+Q555zRX8US3eg2WAmJl/abPZbT1JwK6G4peFRbtNAoW7aJ+zFnmywWQ7qxFO/QCtE+x8b3dUcTvSO8vQ27hy0P6xxjKBfgDsQ7HJhsOVGtGC5VcUn3KqFFhhtNe8NK/EU=
